### ISSUE TITLE
wrong pointer to SikuliX docs 

### ISSUE THREAD

**Issue by RaiMan** [cicerohellmann/Sikumber#1]
This is RaiMan from SikuliX.

Since you are using SikuliX 1.1.0, the docs pointer in your ReadMe should be:
http://sikulix-2014.readthedocs.org/en/latest/index.html

thanks for your usage example.

**Comment by cicerohellmann** [comment]
Thank you
:)

Cicero Hellmann Jacobi
+55 48 96483133
Mobile Developer
